# Generated by Django 2.0 on 2019-07-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('nutrition_score', models.CharField(max_length=5)),
                ('nutrition_100', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ManyToManyField(related_name='cat_product', to='research.Category')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
